#!/usr/bin/python
#
# Copyright (c) 2012 Citrix Systems, Inc.
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#

#
# Generates a bash completion script for the sync-admin command.
#
# The resulting script is intended to be installed in /etc/bash_completion.d,
# but for testing purposes it can be sourced directly:
#
#    ./generate-completion > completion
#    . completion

import argparse
import os
import sys

try:
    import sync_db
except ImportError:
    # Useful when running from source tree.
    sys.path.append(os.path.join(os.path.dirname(__file__), os.pardir,
                                 "sync-database"))
    import sync_db

import sync_cli.main
import sync_cli.add_disk
import sync_cli_completion.main

parser = sync_cli.main.create_parser()

sys.stdout.write(sync_cli_completion.main.format_script(
    parser,
    sync_cli.add_disk.DISK_TYPES))
